version: '2'
services:
  dnsmasq:
    image: registry.cn-shenzhen.aliyuncs.com/jonath/dnsmasq
    container_name: dnsmasq
    restart: always
    ports: 
    - "8053:53/udp"
    - "5380:5380"
    environment:
      HTTP_USER: admin
      HTTP_PASS: admin
